In [1]:
import pandas as pd
import numpy as np
f = input("Enter the path to the rank file: ")
f1 = input("Enter the path to the route file: ")
rank = pd.read_excel(f, sheet_name='Rank',index_col=None, header=None)
rank = rank.iloc[1:, 1:].values

In [2]:
print(rank)

[[28 48 54 81 91 92 124 131 145 176 206 231 244 255 264]
 [9 22 47 79 109 115 133 136 144 152 163 180 209 216 283]
 [6 36 53 70 83 104 137 146 202 205 260 275 276 291 299]
 [20 59 61 85 113 127 139 157 187 213 246 250 262 290 294]
 [5 43 60 88 95 96 101 143 166 173 178 195 233 277 292]
 [14 15 44 49 87 89 100 107 182 196 221 234 269 270 293]
 [34 82 103 110 111 119 149 153 165 169 190 194 256 271 297]
 [13 30 35 40 73 93 122 126 142 189 215 220 245 252 296]
 [16 31 71 106 118 125 155 158 168 177 211 218 227 259 263]
 [32 50 55 74 98 128 129 179 224 226 240 267 272 286 295]
 [11 17 46 62 65 108 148 167 192 199 201 214 219 280 288]
 [1 8 38 76 138 150 171 183 185 200 230 239 261 273 282]
 [2 18 21 37 58 66 72 102 123 204 208 217 258 281 284]
 [23 69 75 121 134 156 162 164 188 228 232 238 248 268 300]
 [42 51 63 112 132 135 160 181 197 225 237 251 253 274 298]
 [7 33 41 52 78 90 97 151 161 184 222 236 241 287 289]
 [4 19 45 64 84 94 117 141 147 159 170 203 210 235 278]
 [12 26 29 56 68 10

In [3]:
jobs = len(rank)
operations = len(rank[0])
print(jobs)
print(operations)
tmp = [[] for _ in range(jobs * operations)]
print(tmp)


20
15
[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [

In [4]:
for i in range(len(rank)):
    for j in range(len(rank[0])):
        tmp[rank[i][j]-1] = [i+1, j+1]

print(tmp)
        

[[12, 1], [13, 1], [19, 1], [17, 1], [5, 1], [3, 1], [16, 1], [12, 2], [2, 1], [20, 1], [11, 1], [18, 1], [8, 1], [6, 1], [6, 2], [9, 1], [11, 2], [13, 2], [17, 2], [4, 1], [13, 3], [2, 2], [14, 1], [19, 2], [20, 2], [18, 2], [20, 3], [1, 1], [18, 3], [8, 2], [9, 2], [10, 1], [16, 2], [7, 1], [8, 3], [3, 2], [13, 4], [12, 3], [19, 3], [8, 4], [16, 3], [15, 1], [5, 2], [6, 3], [17, 3], [11, 3], [2, 3], [1, 2], [6, 4], [10, 2], [15, 2], [16, 4], [3, 3], [1, 3], [10, 3], [18, 4], [20, 4], [13, 5], [4, 2], [5, 3], [4, 3], [11, 4], [15, 3], [17, 4], [11, 5], [13, 6], [19, 4], [18, 5], [14, 2], [3, 4], [9, 3], [13, 7], [8, 5], [10, 4], [14, 3], [12, 4], [19, 5], [16, 5], [2, 4], [20, 5], [1, 4], [7, 2], [3, 5], [17, 5], [4, 4], [20, 6], [6, 5], [5, 4], [6, 6], [16, 6], [1, 5], [1, 6], [8, 6], [17, 6], [5, 5], [5, 6], [16, 7], [10, 5], [19, 6], [6, 7], [5, 7], [13, 8], [7, 3], [3, 6], [18, 6], [9, 4], [6, 8], [11, 6], [2, 5], [7, 4], [7, 5], [15, 4], [4, 5], [18, 7], [2, 6], [20, 7], [17, 7],

In [5]:
route = pd.read_excel(f1, sheet_name='Sheet1',index_col=None, header=None)
#print(route)
route_array = route.iloc[1:, 1:].values
#print(route_array)
machine = [[] for i in range(operations)]
print(machine)
for i in tmp:
    #print(i)
    #print(route_array[i[1]-1][3*(i[0]-1)])
    machine[int(route_array[i[1]-1][3*(i[0]-1)].split('_')[1]) - 1].append(i[0])

print(machine)

[[], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
[[18, 6, 12, 8, 7, 1, 17, 2, 9, 20, 10, 16, 3, 15, 14, 5, 13, 4, 19, 11], [20, 18, 16, 8, 13, 19, 3, 6, 4, 10, 11, 17, 2, 12, 1, 15, 7, 9, 5, 14], [3, 17, 2, 18, 13, 16, 4, 15, 1, 7, 9, 6, 14, 5, 19, 20, 8, 10, 12, 11], [11, 14, 7, 10, 1, 20, 16, 6, 9, 4, 17, 5, 12, 19, 15, 13, 2, 8, 18, 3], [19, 13, 5, 1, 20, 2, 17, 4, 14, 8, 7, 18, 9, 11, 6, 10, 16, 15, 3, 12], [4, 13, 10, 20, 8, 16, 5, 19, 7, 18, 3, 17, 11, 9, 12, 15, 6, 1, 2, 14], [19, 5, 15, 4, 11, 10, 18, 9, 3, 14, 20, 17, 6, 16, 8, 1, 12, 7, 13, 2], [13, 15, 11, 3, 17, 9, 2, 4, 10, 1, 7, 5, 20, 6, 12, 8, 18, 19, 14, 16], [13, 1, 9, 2, 18, 3, 17, 7, 8, 5, 15, 11, 20, 10, 14, 12, 4, 19, 6, 16], [20, 19, 8, 11, 13, 17, 5, 2, 14, 12, 16, 18, 7, 3, 1, 4, 9, 6, 10, 15], [16, 12, 6, 20, 5, 1, 14, 8, 3, 18, 15, 19, 7, 2, 13, 17, 11, 9, 10, 4], [17, 8, 9, 5, 4, 6, 11, 2, 15, 1, 12, 16, 7, 20, 14, 18, 3, 13, 19, 10], [12, 11, 3, 6, 10, 19, 8, 13, 1, 2, 14, 5, 9, 16, 15, 20, 18, 

In [6]:
import pandas as pd
from openpyxl import load_workbook


# Create column names
col_names = ['Seq' + str(i) for i in range(1, len(machine[0])+1)]

# Create row names
row_names = ['Machine' + str(i) for i in range(1, len(machine)+1)]

# Convert the 2D array into pandas DataFrame and specify column names and row names
df = pd.DataFrame(machine, columns=col_names, index=row_names)

# Use openpyxl to load an existing Excel file
book = load_workbook(f)

# If the worksheet exists, use it; otherwise, create it
if 'Sequence' in book.sheetnames:
    writer_sheets = book['Sequence']
else:
    writer_sheets = book.create_sheet('Sequence')

# Write DataFrame into Excel worksheet
for index, row in df.iterrows():
    writer_sheets.append(list(row))

# Save file
book.save(f)
